"""영어 듣기 — capcha_service ms english 02-sound-match 이식(원본 25문항 구조 그대로).

원본 5단계: 1~3단계 pick(그림+단어 라벨, showLabel), 4단계 pick(라벨 숨김·재생 2회 제한),
5단계 sequence(연속듣기 — 들린 순서대로 탭). 오디오는 불투명 이름(snd-NN.m4a)으로 서빙.
교육용 행동수집 API — 라벨 표시는 원본 학습 설계를 따른다(봇 차단이 목적이 아님).
"""

ENGLISH_LISTEN: list[dict] = [
    {'id': 'eng-listen-s1-q1', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍇', 'text': 'grape'}, {'id': 'o2', 'emoji': '🐦', 'text': 'bird'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'grape', 'showLabel': True, 'audio': 'snd-16.m4a'},
    {'id': 'eng-listen-s1-q2', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🐮', 'text': 'cow'}, {'id': 'o2', 'emoji': '🐦', 'text': 'bird'}], 'answer': 'o2', 'playable': 'o2', 'explain': 'bird', 'showLabel': True, 'audio': 'snd-06.m4a'},
    {'id': 'eng-listen-s1-q3', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🧢', 'text': 'cap'}, {'id': 'o2', 'emoji': '🍊', 'text': 'orange'}], 'answer': 'o2', 'playable': 'o2', 'explain': 'orange', 'showLabel': True, 'audio': 'snd-18.m4a'},
    {'id': 'eng-listen-s1-q4', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🟢', 'text': 'green'}, {'id': 'o2', 'emoji': '✏️', 'text': 'pencil'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'green', 'showLabel': True, 'audio': 'snd-17.m4a'},
    {'id': 'eng-listen-s1-q5', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🎒', 'text': 'bag'}, {'id': 'o2', 'emoji': '🪑', 'text': 'chair'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'bag', 'showLabel': True, 'audio': 'snd-02.m4a'},
    {'id': 'eng-listen-s2-q1', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '영어 단어를 잘 듣고 알맞은 그림을 선택해요.', 'hint': '🔊 소리를 듣고 4개 중에서 골라요.', 'options': [{'id': 'o1', 'emoji': '🪑', 'text': 'chair'}, {'id': 'o2', 'emoji': '🟢', 'text': 'green'}, {'id': 'o3', 'emoji': '⚽', 'text': 'ball'}, {'id': 'o4', 'emoji': '🔵', 'text': 'blue'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'chair', 'showLabel': True, 'audio': 'snd-12.m4a'},
    {'id': 'eng-listen-s2-q2', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '영어 단어를 잘 듣고 알맞은 그림을 선택해요.', 'hint': '🔊 소리를 듣고 4개 중에서 골라요.', 'options': [{'id': 'o1', 'emoji': '🖊️', 'text': 'pen'}, {'id': 'o2', 'emoji': '🐦', 'text': 'bird'}, {'id': 'o3', 'emoji': '🐟', 'text': 'fish'}, {'id': 'o4', 'emoji': '🟡', 'text': 'yellow'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'pen', 'showLabel': True, 'audio': 'snd-21.m4a'},
    {'id': 'eng-listen-s2-q3', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '영어 단어를 잘 듣고 알맞은 그림을 선택해요.', 'hint': '🔊 소리를 듣고 4개 중에서 골라요.', 'options': [{'id': 'o1', 'emoji': '🐶', 'text': 'dog'}, {'id': 'o2', 'emoji': '🍎', 'text': 'apple'}, {'id': 'o3', 'emoji': '🧢', 'text': 'cap'}, {'id': 'o4', 'emoji': '🚗', 'text': 'car'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'dog', 'showLabel': True, 'audio': 'snd-14.m4a'},
    {'id': 'eng-listen-s2-q4', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '영어 단어를 잘 듣고 알맞은 그림을 선택해요.', 'hint': '🔊 소리를 듣고 4개 중에서 골라요.', 'options': [{'id': 'o1', 'emoji': '🍐', 'text': 'pear'}, {'id': 'o2', 'emoji': '🧢', 'text': 'cap'}, {'id': 'o3', 'emoji': '🍊', 'text': 'orange'}, {'id': 'o4', 'emoji': '🔴', 'text': 'red'}], 'answer': 'o2', 'playable': 'o2', 'explain': 'cap', 'showLabel': True, 'audio': 'snd-09.m4a'},
    {'id': 'eng-listen-s2-q5', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '영어 단어를 잘 듣고 알맞은 그림을 선택해요.', 'hint': '🔊 소리를 듣고 4개 중에서 골라요.', 'options': [{'id': 'o1', 'emoji': '✏️', 'text': 'pencil'}, {'id': 'o2', 'emoji': '🐱', 'text': 'cat'}, {'id': 'o3', 'emoji': '🐶', 'text': 'dog'}, {'id': 'o4', 'emoji': '🍌', 'text': 'banana'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'pencil', 'showLabel': True, 'audio': 'snd-22.m4a'},
    {'id': 'eng-listen-s3-q1', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '비슷한 소리를 잘 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 발음을 여러 번 들어봐도 좋아요.', 'options': [{'id': 'o1', 'emoji': '📘', 'text': 'book'}, {'id': 'o2', 'emoji': '🎒', 'text': 'bag'}, {'id': 'o3', 'emoji': '🐦', 'text': 'bird'}, {'id': 'o4', 'emoji': '⚽', 'text': 'ball'}], 'answer': 'o4', 'playable': 'o4', 'explain': 'ball', 'showLabel': True, 'audio': 'snd-03.m4a'},
    {'id': 'eng-listen-s3-q2', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '비슷한 소리를 잘 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 발음을 여러 번 들어봐도 좋아요.', 'options': [{'id': 'o1', 'emoji': '🚗', 'text': 'car'}, {'id': 'o2', 'emoji': '🐱', 'text': 'cat'}, {'id': 'o3', 'emoji': '🐮', 'text': 'cow'}, {'id': 'o4', 'emoji': '🧢', 'text': 'cap'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'car', 'showLabel': True, 'audio': 'snd-10.m4a'},
    {'id': 'eng-listen-s3-q3', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '비슷한 소리를 잘 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 발음을 여러 번 들어봐도 좋아요.', 'options': [{'id': 'o1', 'emoji': '🐻', 'text': 'bear'}, {'id': 'o2', 'emoji': '🔵', 'text': 'blue'}, {'id': 'o3', 'emoji': '📘', 'text': 'book'}, {'id': 'o4', 'emoji': '🍌', 'text': 'banana'}], 'answer': 'o4', 'playable': 'o4', 'explain': 'banana', 'showLabel': True, 'audio': 'snd-04.m4a'},
    {'id': 'eng-listen-s3-q4', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '비슷한 소리를 잘 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 발음을 여러 번 들어봐도 좋아요.', 'options': [{'id': 'o1', 'emoji': '🍑', 'text': 'peach'}, {'id': 'o2', 'emoji': '🍐', 'text': 'pear'}, {'id': 'o3', 'emoji': '🐻', 'text': 'bear'}, {'id': 'o4', 'emoji': '🖊️', 'text': 'pen'}], 'answer': 'o2', 'playable': 'o2', 'explain': 'pear', 'showLabel': True, 'audio': 'snd-20.m4a'},
    {'id': 'eng-listen-s3-q5', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '비슷한 소리를 잘 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 발음을 여러 번 들어봐도 좋아요.', 'options': [{'id': 'o1', 'emoji': '🍐', 'text': 'pear'}, {'id': 'o2', 'emoji': '🖊️', 'text': 'pen'}, {'id': 'o3', 'emoji': '✏️', 'text': 'pencil'}, {'id': 'o4', 'emoji': '🍑', 'text': 'peach'}], 'answer': 'o4', 'playable': 'o4', 'explain': 'peach', 'showLabel': True, 'audio': 'snd-19.m4a'},
    {'id': 'eng-listen-s4-q1', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '단어를 듣고 그림만 보고 맞혀보세요.', 'hint': '🔊 오디오는 2번까지만 들을 수 있어요.', 'options': [{'id': 'o1', 'emoji': '🖊️', 'text': ''}, {'id': 'o2', 'emoji': '🐻', 'text': ''}, {'id': 'o3', 'emoji': '🐟', 'text': ''}, {'id': 'o4', 'emoji': '🍊', 'text': ''}], 'answer': 'o3', 'playable': 'o3', 'explain': 'fish', 'plays': 2, 'audio': 'snd-15.m4a'},
    {'id': 'eng-listen-s4-q2', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '단어를 듣고 그림만 보고 맞혀보세요.', 'hint': '🔊 오디오는 2번까지만 들을 수 있어요.', 'options': [{'id': 'o1', 'emoji': '⚽', 'text': ''}, {'id': 'o2', 'emoji': '🔴', 'text': ''}, {'id': 'o3', 'emoji': '🐮', 'text': ''}, {'id': 'o4', 'emoji': '🍑', 'text': ''}], 'answer': 'o3', 'playable': 'o3', 'explain': 'cow', 'plays': 2, 'audio': 'snd-13.m4a'},
    {'id': 'eng-listen-s4-q3', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '단어를 듣고 그림만 보고 맞혀보세요.', 'hint': '🔊 오디오는 2번까지만 들을 수 있어요.', 'options': [{'id': 'o1', 'emoji': '🐱', 'text': ''}, {'id': 'o2', 'emoji': '🍌', 'text': ''}, {'id': 'o3', 'emoji': '🐮', 'text': ''}, {'id': 'o4', 'emoji': '🍎', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'explain': 'cat', 'plays': 2, 'audio': 'snd-11.m4a'},
    {'id': 'eng-listen-s4-q4', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '단어를 듣고 그림만 보고 맞혀보세요.', 'hint': '🔊 오디오는 2번까지만 들을 수 있어요.', 'options': [{'id': 'o1', 'emoji': '🐦', 'text': ''}, {'id': 'o2', 'emoji': '🚗', 'text': ''}, {'id': 'o3', 'emoji': '🍌', 'text': ''}, {'id': 'o4', 'emoji': '📘', 'text': ''}], 'answer': 'o4', 'playable': 'o4', 'explain': 'book', 'plays': 2, 'audio': 'snd-08.m4a'},
    {'id': 'eng-listen-s4-q5', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '단어를 듣고 그림만 보고 맞혀보세요.', 'hint': '🔊 오디오는 2번까지만 들을 수 있어요.', 'options': [{'id': 'o1', 'emoji': '🔴', 'text': ''}, {'id': 'o2', 'emoji': '🐮', 'text': ''}, {'id': 'o3', 'emoji': '🍊', 'text': ''}, {'id': 'o4', 'emoji': '🍐', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'explain': 'red', 'plays': 2, 'audio': 'snd-23.m4a'},
    {'id': 'eng-listen-seq-s5-q1', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen_seq', 'prompt': '소리를 듣고 순서대로 그림을 골라보세요.', 'hint': '🔊 들린 순서 그대로 눌러요.', 'options': [{'id': 'o1', 'emoji': '🟡', 'text': 'yellow'}, {'id': 'o2', 'emoji': '🐻', 'text': 'bear'}, {'id': 'o3', 'emoji': '🔴', 'text': 'red'}, {'id': 'o4', 'emoji': '🍊', 'text': 'orange'}], 'answer': ['o2', 'o1'], 'playable': True, 'explain': 'bear → yellow', 'showLabel': True, 'audios': ['snd-05.m4a', 'snd-24.m4a']},
    {'id': 'eng-listen-seq-s5-q2', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen_seq', 'prompt': '소리를 듣고 순서대로 그림을 골라보세요.', 'hint': '🔊 단어 3개! 순서를 기억해요.', 'options': [{'id': 'o1', 'emoji': '🧢', 'text': 'cap'}, {'id': 'o2', 'emoji': '🍎', 'text': 'apple'}, {'id': 'o3', 'emoji': '🖊️', 'text': 'pen'}, {'id': 'o4', 'emoji': '🔵', 'text': 'blue'}], 'answer': ['o4', 'o2', 'o3'], 'playable': True, 'explain': 'blue → apple → pen', 'showLabel': True, 'audios': ['snd-07.m4a', 'snd-01.m4a', 'snd-21.m4a']},
    {'id': 'eng-listen-seq-s5-q3', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen_seq', 'prompt': '소리를 듣고 순서대로 그림을 골라보세요.', 'hint': '🔊 들린 순서 그대로 눌러요.', 'options': [{'id': 'o1', 'emoji': '🍌', 'text': 'banana'}, {'id': 'o2', 'emoji': '🍐', 'text': 'pear'}, {'id': 'o3', 'emoji': '🟢', 'text': 'green'}, {'id': 'o4', 'emoji': '🐮', 'text': 'cow'}], 'answer': ['o3', 'o2'], 'playable': True, 'explain': 'green → pear', 'showLabel': True, 'audios': ['snd-17.m4a', 'snd-20.m4a']},
    {'id': 'eng-listen-seq-s5-q4', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen_seq', 'prompt': '소리를 듣고 순서대로 그림을 골라보세요.', 'hint': '🔊 단어 3개! 순서를 기억해요.', 'options': [{'id': 'o1', 'emoji': '🐱', 'text': 'cat'}, {'id': 'o2', 'emoji': '🍇', 'text': 'grape'}, {'id': 'o3', 'emoji': '🖊️', 'text': 'pen'}, {'id': 'o4', 'emoji': '🧢', 'text': 'cap'}], 'answer': ['o4', 'o1', 'o3'], 'playable': True, 'explain': 'cap → cat → pen', 'showLabel': True, 'audios': ['snd-09.m4a', 'snd-11.m4a', 'snd-21.m4a']},
    {'id': 'eng-listen-seq-s5-q5', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen_seq', 'prompt': '소리를 듣고 순서대로 그림을 골라보세요.', 'hint': '🔊 들린 순서 그대로 눌러요.', 'options': [{'id': 'o1', 'emoji': '🍇', 'text': 'grape'}, {'id': 'o2', 'emoji': '🍌', 'text': 'banana'}, {'id': 'o3', 'emoji': '🎒', 'text': 'bag'}, {'id': 'o4', 'emoji': '🔵', 'text': 'blue'}], 'answer': ['o2', 'o4'], 'playable': True, 'explain': 'banana → blue', 'showLabel': True, 'audios': ['snd-04.m4a', 'snd-07.m4a']},
]

# 서빙 허용 오디오 파일 화이트리스트 (경로 조작 차단용) — 단일(audio)·연속듣기(audios) 모두
AUDIO_FILES = frozenset(
    f for q in ENGLISH_LISTEN
    for f in ([q["audio"]] if "audio" in q else q.get("audios", []))
)
