"""stat_blobs

Revision ID: 44b65184828f
Revises: dbd1e5284169
Create Date: 2026-07-04 10:38:51.595857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44b65184828f'
down_revision: Union[str, None] = 'dbd1e5284169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_blobs',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_stat_org_key')
    )
    op.create_index(op.f('ix_stat_blobs_key'), 'stat_blobs', ['key'], unique=False)
    op.create_index(op.f('ix_stat_blobs_organization_id'), 'stat_blobs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stat_blobs_organization_id'), table_name='stat_blobs')
    op.drop_index(op.f('ix_stat_blobs_key'), table_name='stat_blobs')
    op.drop_table('stat_blobs')
    # ### end Alembic commands ###
