"""login_throttle

Revision ID: 45ac9a136734
Revises: 44b65184828f
Create Date: 2026-07-04 11:54:50.729302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45ac9a136734'
down_revision: Union[str, None] = '44b65184828f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_throttle',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_throttle_identifier'), 'login_throttle', ['identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_throttle_identifier'), table_name='login_throttle')
    op.drop_table('login_throttle')
    # ### end Alembic commands ###
