"""unique_student_login_id

Revision ID: bd27a963365f
Revises: 45ac9a136734
Create Date: 2026-07-04 14:58:42.788786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd27a963365f'
down_revision: Union[str, None] = '45ac9a136734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # MySQL DDL은 비트랜잭션 — 중단 후 재실행해도 안전하도록 현재 상태를 확인하고 진행
    bind = op.get_bind()
    rows = bind.execute(
        sa.text("SHOW INDEX FROM student_profiles WHERE Key_name = 'ix_student_profiles_student_login_id'")
    ).fetchall()
    if rows:
        # Non_unique == 0 이면 이미 unique — 완료 상태
        if all(r[1] == 0 for r in rows):
            return
        op.drop_index(op.f('ix_student_profiles_student_login_id'), table_name='student_profiles')
    op.create_index(
        op.f('ix_student_profiles_student_login_id'),
        'student_profiles',
        ['student_login_id'],
        unique=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_student_login_id'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_student_login_id'), 'student_profiles', ['student_login_id'], unique=False)
    # ### end Alembic commands ###
