"""initial schema

Revision ID: dbd1e5284169
Revises: 
Create Date: 2026-07-03 23:11:37.358191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbd1e5284169'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('site_id', sa.CHAR(length=36), nullable=True),
    sa.Column('endpoint', sa.String(length=150), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_organization_id'), 'api_usage_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_site_id'), 'api_usage_logs', ['site_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('actor_user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.CHAR(length=36), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('badges',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('condition_text', sa.String(length=200), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior_summaries',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('solve_time_ms', sa.Integer(), nullable=False),
    sa.Column('path_length', sa.Float(), nullable=False),
    sa.Column('avg_speed', sa.Float(), nullable=False),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('drop_distance_norm', sa.Float(), nullable=False),
    sa.Column('interaction_result', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_summaries_organization_id'), 'behavior_summaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_behavior_summaries_student_id'), 'behavior_summaries', ['student_id'], unique=False)
    op.create_table('captcha_assets',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('ai_label', sa.String(length=60), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captcha_assets_organization_id'), 'captcha_assets', ['organization_id'], unique=False)
    op.create_table('chapters',
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('concept', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_subject'), 'chapters', ['subject'], unique=False)
    op.create_table('contents',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=30), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('route_hint', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_category'), 'contents', ['category'], unique=False)
    op.create_index(op.f('ix_contents_organization_id'), 'contents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contents_subject'), 'contents', ['subject'], unique=False)
    op.create_table('email_logs',
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.create_table('email_verification_codes',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_codes_code_hash'), 'email_verification_codes', ['code_hash'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_email'), 'email_verification_codes', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_codes_user_id'), 'email_verification_codes', ['user_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('inquiry_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('affiliation', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutions',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('inst_type', sa.String(length=30), nullable=False),
    sa.Column('sido', sa.String(length=30), nullable=False),
    sa.Column('sigungu', sa.String(length=30), nullable=False),
    sa.Column('dong', sa.String(length=30), nullable=False),
    sa.Column('road_address', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_dong'), 'institutions', ['dong'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_sido'), 'institutions', ['sido'], unique=False)
    op.create_index(op.f('ix_institutions_sigungu'), 'institutions', ['sigungu'], unique=False)
    op.create_table('invoices',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('invoice_no', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billed_on', sa.String(length=20), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_on', sa.String(length=30), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('student_id', sa.CHAR(length=36), nullable=True),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('child_id', sa.CHAR(length=36), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_student_id'), 'notifications', ['student_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('org_registration_requests',
    sa.Column('org_name', sa.String(length=150), nullable=False),
    sa.Column('org_type', sa.String(length=30), nullable=False),
    sa.Column('business_number', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('expected_students', sa.String(length=30), nullable=True),
    sa.Column('plan_interest', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('org_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('business_number', sa.String(length=30), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_number')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('card_brand', sa.String(length=30), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_organization_id'), 'payment_methods', ['organization_id'], unique=False)
    op.create_table('plans',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('monthly_price', sa.Integer(), nullable=False),
    sa.Column('yearly_price', sa.Integer(), nullable=False),
    sa.Column('api_quota', sa.Integer(), nullable=False),
    sa.Column('student_seats', sa.Integer(), nullable=False),
    sa.Column('teacher_seats', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=10), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_student_id'), 'reports', ['student_id'], unique=False)
    op.create_table('shop_items',
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_items_category'), 'shop_items', ['category'], unique=False)
    op.create_table('system_health_logs',
    sa.Column('service_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('subject_type', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.CHAR(length=36), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_subject_id'), 'user_settings', ['subject_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('asset_id', sa.CHAR(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('predicted_label', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['captcha_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_asset_id'), 'ai_predictions', ['asset_id'], unique=False)
    op.create_table('captcha_settings',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('active_types', sa.JSON(), nullable=False),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('shuffle', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captcha_settings_organization_id'), 'captcha_settings', ['organization_id'], unique=True)
    op.create_table('classes',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.String(length=30), nullable=True),
    sa.Column('teacher_id', sa.CHAR(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_organization_id'), 'classes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_classes_teacher_id'), 'classes', ['teacher_id'], unique=False)
    op.create_table('invitations',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.CHAR(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('teacher_code', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('career_years', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.CHAR(length=36), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_code')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('report_download_logs',
    sa.Column('report_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_download_logs_report_id'), 'report_download_logs', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_download_logs_user_id'), 'report_download_logs', ['user_id'], unique=False)
    op.create_table('sites',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('allowed_origins', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('plan_id', sa.CHAR(length=36), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=True)
    op.create_table('api_keys',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('site_id', sa.CHAR(length=36), nullable=False),
    sa.Column('site_key', sa.String(length=64), nullable=False),
    sa.Column('secret_key_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_site_id'), 'api_keys', ['site_id'], unique=False)
    op.create_index(op.f('ix_api_keys_site_key'), 'api_keys', ['site_key'], unique=True)
    op.create_table('student_profiles',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('class_id', sa.CHAR(length=36), nullable=True),
    sa.Column('student_login_id', sa.String(length=50), nullable=False),
    sa.Column('student_code', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('grade_band', sa.String(length=30), nullable=False),
    sa.Column('avatar', sa.JSON(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_class_id'), 'student_profiles', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_organization_id'), 'student_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_student_code'), 'student_profiles', ['student_code'], unique=True)
    op.create_index(op.f('ix_student_profiles_student_login_id'), 'student_profiles', ['student_login_id'], unique=False)
    op.create_table('coin_transactions',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_transactions_student_id'), 'coin_transactions', ['student_id'], unique=False)
    op.create_table('concept_reads',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('chapter_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_reads_chapter_id'), 'concept_reads', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_concept_reads_student_id'), 'concept_reads', ['student_id'], unique=False)
    op.create_table('daily_quiz_status',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('quiz_date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quiz_status_quiz_date'), 'daily_quiz_status', ['quiz_date'], unique=False)
    op.create_index(op.f('ix_daily_quiz_status_student_id'), 'daily_quiz_status', ['student_id'], unique=False)
    op.create_table('family_messages',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('teacher_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_messages_organization_id'), 'family_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_family_messages_student_id'), 'family_messages', ['student_id'], unique=False)
    op.create_index(op.f('ix_family_messages_teacher_id'), 'family_messages', ['teacher_id'], unique=False)
    op.create_table('learning_attempts',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.CHAR(length=36), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('solve_time_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('estimated_reason', sa.String(length=50), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_attempts_organization_id'), 'learning_attempts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learning_attempts_student_id'), 'learning_attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_learning_attempts_subject'), 'learning_attempts', ['subject'], unique=False)
    op.create_table('learning_summaries',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('average_solve_time_ms', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('strength_tags', sa.JSON(), nullable=False),
    sa.Column('need_practice_tags', sa.JSON(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_summaries_organization_id'), 'learning_summaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learning_summaries_student_id'), 'learning_summaries', ['student_id'], unique=False)
    op.create_table('parent_student_links',
    sa.Column('parent_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.CHAR(length=36), nullable=True),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.Column('time_limit_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_student_links_organization_id'), 'parent_student_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_parent_user_id'), 'parent_student_links', ['parent_user_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_student_id'), 'parent_student_links', ['student_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_table('student_badges',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('badge_id', sa.CHAR(length=36), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_badges_badge_id'), 'student_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_student_badges_student_id'), 'student_badges', ['student_id'], unique=False)
    op.create_table('student_items',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_items_item_id'), 'student_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_student_items_student_id'), 'student_items', ['student_id'], unique=False)
    op.create_table('student_progress',
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('chapters_done', sa.Integer(), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=False),
    sa.Column('questions_done', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_progress_organization_id'), 'student_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_student_progress_student_id'), 'student_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_progress_subject'), 'student_progress', ['subject'], unique=False)
    op.create_table('wrong_answers',
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('my_answer', sa.String(length=200), nullable=False),
    sa.Column('correct_answer', sa.String(length=200), nullable=False),
    sa.Column('tip', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('wrong_date', sa.Date(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wrong_answers_organization_id'), 'wrong_answers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_wrong_answers_student_id'), 'wrong_answers', ['student_id'], unique=False)
    op.create_index(op.f('ix_wrong_answers_subject'), 'wrong_answers', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wrong_answers_subject'), table_name='wrong_answers')
    op.drop_index(op.f('ix_wrong_answers_student_id'), table_name='wrong_answers')
    op.drop_index(op.f('ix_wrong_answers_organization_id'), table_name='wrong_answers')
    op.drop_table('wrong_answers')
    op.drop_index(op.f('ix_student_progress_subject'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_student_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_organization_id'), table_name='student_progress')
    op.drop_table('student_progress')
    op.drop_index(op.f('ix_student_items_student_id'), table_name='student_items')
    op.drop_index(op.f('ix_student_items_item_id'), table_name='student_items')
    op.drop_table('student_items')
    op.drop_index(op.f('ix_student_badges_student_id'), table_name='student_badges')
    op.drop_index(op.f('ix_student_badges_badge_id'), table_name='student_badges')
    op.drop_table('student_badges')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_parent_student_links_student_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_parent_user_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_organization_id'), table_name='parent_student_links')
    op.drop_table('parent_student_links')
    op.drop_index(op.f('ix_learning_summaries_student_id'), table_name='learning_summaries')
    op.drop_index(op.f('ix_learning_summaries_organization_id'), table_name='learning_summaries')
    op.drop_table('learning_summaries')
    op.drop_index(op.f('ix_learning_attempts_subject'), table_name='learning_attempts')
    op.drop_index(op.f('ix_learning_attempts_student_id'), table_name='learning_attempts')
    op.drop_index(op.f('ix_learning_attempts_organization_id'), table_name='learning_attempts')
    op.drop_table('learning_attempts')
    op.drop_index(op.f('ix_family_messages_teacher_id'), table_name='family_messages')
    op.drop_index(op.f('ix_family_messages_student_id'), table_name='family_messages')
    op.drop_index(op.f('ix_family_messages_organization_id'), table_name='family_messages')
    op.drop_table('family_messages')
    op.drop_index(op.f('ix_daily_quiz_status_student_id'), table_name='daily_quiz_status')
    op.drop_index(op.f('ix_daily_quiz_status_quiz_date'), table_name='daily_quiz_status')
    op.drop_table('daily_quiz_status')
    op.drop_index(op.f('ix_concept_reads_student_id'), table_name='concept_reads')
    op.drop_index(op.f('ix_concept_reads_chapter_id'), table_name='concept_reads')
    op.drop_table('concept_reads')
    op.drop_index(op.f('ix_coin_transactions_student_id'), table_name='coin_transactions')
    op.drop_table('coin_transactions')
    op.drop_index(op.f('ix_student_profiles_student_login_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_student_code'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_organization_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_class_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_api_keys_site_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_site_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_report_download_logs_user_id'), table_name='report_download_logs')
    op.drop_index(op.f('ix_report_download_logs_report_id'), table_name='report_download_logs')
    op.drop_table('report_download_logs')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_classes_teacher_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_organization_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_captcha_settings_organization_id'), table_name='captcha_settings')
    op.drop_table('captcha_settings')
    op.drop_index(op.f('ix_ai_predictions_asset_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_settings_subject_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_table('system_health_logs')
    op.drop_index(op.f('ix_shop_items_category'), table_name='shop_items')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_reports_student_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('plans')
    op.drop_index(op.f('ix_payment_methods_organization_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('org_registration_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_student_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_institutions_sigungu'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_sido'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_dong'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_email_verification_codes_user_id'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_email'), table_name='email_verification_codes')
    op.drop_index(op.f('ix_email_verification_codes_code_hash'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_contents_subject'), table_name='contents')
    op.drop_index(op.f('ix_contents_organization_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_category'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_chapters_subject'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_captcha_assets_organization_id'), table_name='captcha_assets')
    op.drop_table('captcha_assets')
    op.drop_index(op.f('ix_behavior_summaries_student_id'), table_name='behavior_summaries')
    op.drop_index(op.f('ix_behavior_summaries_organization_id'), table_name='behavior_summaries')
    op.drop_table('behavior_summaries')
    op.drop_table('badges')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_usage_logs_site_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_organization_id'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
